### PR TITLE
Updated to use .NET Core RC2

### PR DESCRIPTION
**Pull request by billpratt**

### CODE REVIEW

**Comment by leastprivilege** [comment]
Why do you want to run idsrv3 on core? This is not a combination we test (nor support).

Idsrv3 is designed for Katana - use idsrv4 on core (when it is ready).

**Comment by dotcom9** [comment]
Publishing this change would enable .net core web clients to connect to legacy ID3 SSO systems. This is a configuration that I am currently required to support.

**Comment by leastprivilege** [comment]
There are other options  

a) use the aspnetcore JWT MW
b) use our aspnetcore version of the validation MW

**Comment by leastprivilege** [comment]
any feedback why the above does not work for you?

**Comment by billpratt** [comment]
I thought I needed it but do not. You can close this.

**Pull request closed without merging**
